backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Создана статья «{{slug}}»"
    update: "Обновлена статья «{{slug}}»"
    delete: "Удалена статья «{{slug}}»"
    uploadMedia: "Загружен файл «{{path}}»"
    deleteMedia: "Удален файл «{{path}}»"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Статьи"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }
